/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconHeroiconsBolt20Solid: typeof import('~icons/heroicons/bolt20-solid')['default']
    IconHeroiconsCalendarDays20Solid: typeof import('~icons/heroicons/calendar-days20-solid')['default']
    IconHeroiconsChartBar20Solid: typeof import('~icons/heroicons/chart-bar20-solid')['default']
    IconHeroiconsMapPin20Solid: typeof import('~icons/heroicons/map-pin20-solid')['default']
    IconHeroiconsMegaphone20Solid: typeof import('~icons/heroicons/megaphone20-solid')['default']
    IconHeroiconsSparkles20Solid: typeof import('~icons/heroicons/sparkles20-solid')['default']
    IconHeroiconsTag20Solid: typeof import('~icons/heroicons/tag20-solid')['default']
    IconHeroiconsUserGroup20Solid: typeof import('~icons/heroicons/user-group20-solid')['default']
    IconMdiChartDonut: typeof import('~icons/mdi/chart-donut')['default']
    IconMdiTagMultipleOutline: typeof import('~icons/mdi/tag-multiple-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IconHeroiconsBolt20Solid: typeof import('~icons/heroicons/bolt20-solid')['default']
  const IconHeroiconsCalendarDays20Solid: typeof import('~icons/heroicons/calendar-days20-solid')['default']
  const IconHeroiconsChartBar20Solid: typeof import('~icons/heroicons/chart-bar20-solid')['default']
  const IconHeroiconsMapPin20Solid: typeof import('~icons/heroicons/map-pin20-solid')['default']
  const IconHeroiconsMegaphone20Solid: typeof import('~icons/heroicons/megaphone20-solid')['default']
  const IconHeroiconsSparkles20Solid: typeof import('~icons/heroicons/sparkles20-solid')['default']
  const IconHeroiconsTag20Solid: typeof import('~icons/heroicons/tag20-solid')['default']
  const IconHeroiconsUserGroup20Solid: typeof import('~icons/heroicons/user-group20-solid')['default']
  const IconMdiChartDonut: typeof import('~icons/mdi/chart-donut')['default']
  const IconMdiTagMultipleOutline: typeof import('~icons/mdi/tag-multiple-outline')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}