/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconHeroiconsArrowRight20Solid: typeof import('~icons/heroicons/arrow-right20-solid')['default']
    IconHeroiconsBars3: typeof import('~icons/heroicons/bars3')['default']
    IconHeroiconsBolt20Solid: typeof import('~icons/heroicons/bolt20-solid')['default']
    IconHeroiconsCalendarDays20Solid: typeof import('~icons/heroicons/calendar-days20-solid')['default']
    IconHeroiconsChartBar20Solid: typeof import('~icons/heroicons/chart-bar20-solid')['default']
    IconHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
    IconHeroiconsDocumentPlus: typeof import('~icons/heroicons/document-plus')['default']
    IconHeroiconsMapPin20Solid: typeof import('~icons/heroicons/map-pin20-solid')['default']
    IconHeroiconsMegaphone: typeof import('~icons/heroicons/megaphone')['default']
    IconHeroiconsMegaphone20Outline: typeof import('~icons/heroicons/megaphone20-outline')['default']
    IconHeroiconsMegaphone20Solid: typeof import('~icons/heroicons/megaphone20-solid')['default']
    IconHeroiconsPlusCircle: typeof import('~icons/heroicons/plus-circle')['default']
    IconHeroiconsRectangleGroup: typeof import('~icons/heroicons/rectangle-group')['default']
    IconHeroiconsSparkles: typeof import('~icons/heroicons/sparkles')['default']
    IconHeroiconsSparkles20Solid: typeof import('~icons/heroicons/sparkles20-solid')['default']
    IconHeroiconsTag20Solid: typeof import('~icons/heroicons/tag20-solid')['default']
    IconHeroiconsUserCircle: typeof import('~icons/heroicons/user-circle')['default']
    IconHeroiconsUserGroup20Solid: typeof import('~icons/heroicons/user-group20-solid')['default']
    IconHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiCalendar: typeof import('~icons/mdi/calendar')['default']
    IconMdiChartDonut: typeof import('~icons/mdi/chart-donut')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiEmail: typeof import('~icons/mdi/email')['default']
    IconMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiPhone: typeof import('~icons/mdi/phone')['default']
    IconMdiStarCircle: typeof import('~icons/mdi/star-circle')['default']
    IconMdiTagMultipleOutline: typeof import('~icons/mdi/tag-multiple-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IconHeroiconsArrowRight20Solid: typeof import('~icons/heroicons/arrow-right20-solid')['default']
  const IconHeroiconsBars3: typeof import('~icons/heroicons/bars3')['default']
  const IconHeroiconsBolt20Solid: typeof import('~icons/heroicons/bolt20-solid')['default']
  const IconHeroiconsCalendarDays20Solid: typeof import('~icons/heroicons/calendar-days20-solid')['default']
  const IconHeroiconsChartBar20Solid: typeof import('~icons/heroicons/chart-bar20-solid')['default']
  const IconHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
  const IconHeroiconsDocumentPlus: typeof import('~icons/heroicons/document-plus')['default']
  const IconHeroiconsMapPin20Solid: typeof import('~icons/heroicons/map-pin20-solid')['default']
  const IconHeroiconsMegaphone: typeof import('~icons/heroicons/megaphone')['default']
  const IconHeroiconsMegaphone20Outline: typeof import('~icons/heroicons/megaphone20-outline')['default']
  const IconHeroiconsMegaphone20Solid: typeof import('~icons/heroicons/megaphone20-solid')['default']
  const IconHeroiconsPlusCircle: typeof import('~icons/heroicons/plus-circle')['default']
  const IconHeroiconsRectangleGroup: typeof import('~icons/heroicons/rectangle-group')['default']
  const IconHeroiconsSparkles: typeof import('~icons/heroicons/sparkles')['default']
  const IconHeroiconsSparkles20Solid: typeof import('~icons/heroicons/sparkles20-solid')['default']
  const IconHeroiconsTag20Solid: typeof import('~icons/heroicons/tag20-solid')['default']
  const IconHeroiconsUserCircle: typeof import('~icons/heroicons/user-circle')['default']
  const IconHeroiconsUserGroup20Solid: typeof import('~icons/heroicons/user-group20-solid')['default']
  const IconHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
  const IconMdiAccount: typeof import('~icons/mdi/account')['default']
  const IconMdiCalendar: typeof import('~icons/mdi/calendar')['default']
  const IconMdiChartDonut: typeof import('~icons/mdi/chart-donut')['default']
  const IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
  const IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
  const IconMdiClose: typeof import('~icons/mdi/close')['default']
  const IconMdiEmail: typeof import('~icons/mdi/email')['default']
  const IconMdiFacebook: typeof import('~icons/mdi/facebook')['default']
  const IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
  const IconMdiMenu: typeof import('~icons/mdi/menu')['default']
  const IconMdiPhone: typeof import('~icons/mdi/phone')['default']
  const IconMdiStarCircle: typeof import('~icons/mdi/star-circle')['default']
  const IconMdiTagMultipleOutline: typeof import('~icons/mdi/tag-multiple-outline')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}